// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFileWithDialog() {
  return window['go']['main']['App']['OpenFileWithDialog']();
}

export function RenderMarkdown(arg1) {
  return window['go']['main']['App']['RenderMarkdown'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileWithDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileWithDialog'](arg1, arg2);
}
