// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenFileWithDialog():Promise<main.FileResult>;

export function RenderMarkdown(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileWithDialog(arg1:string,arg2:string):Promise<string>;
