// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presets} from '../models';

export function ExportToPDF(arg1:string,arg2:string):Promise<void>;

export function ListPresets():Promise<Array<string>>;

export function LoadPreset(arg1:string):Promise<presets.Preset>;

export function SavePreset(arg1:presets.Preset):Promise<void>;
