// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToPDF(arg1, arg2) {
  return window['go']['main']['Bridge']['ExportToPDF'](arg1, arg2);
}

export function ListPresets() {
  return window['go']['main']['Bridge']['ListPresets']();
}

export function LoadPreset(arg1) {
  return window['go']['main']['Bridge']['LoadPreset'](arg1);
}

export function SavePreset(arg1) {
  return window['go']['main']['Bridge']['SavePreset'](arg1);
}
